### ISSUE TITLE
Transfer this repository into another place (organization)

### ISSUE THREAD

**Issue by Neustradamus** [freeboxos/freeboxos-bash-api#10]
Dear @JrCs,

Can you move your repository into a GitHub Free organization and add @nbanb owner to continuous the development?
- https://github.com/account/organizations/new

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @JrCs,

It is possible to have an answer?

Thanks in advance.

**Comment by nbanb** [comment]
Dear JrCs

Could you please merge and transfer the repository as asked ?

Thanks
Kind regards
nbanba

**Comment by nbanb** [comment]
Here is the current status (commit a few minutes ago)

![image](https://github.com/user-attachments/assets/ff84ca77-b551-42eb-a30c-e8b77f1ec1a0)

Regards
nbanba

**Comment by Neustradamus** [comment]
@JrCs: I have sent you an e-mail few seconds ago.

Thanks in advance.

**Comment by Neustradamus** [comment]
@JrCs is alive, I think, I have seen a commit 16 July 2024 in another repository.

**Comment by nbanb** [comment]
Do you really think @JrCs will review for merging the new 5000 lines of code and 5000 new lines of README on an initial project of 200 lines he wrote 11 years ago and where the original 200 lignes of code don't work anymore since years and years (no TLS support, openssl <1.1.1n ..., only GET and POST methode, no websocket support ... ) ?

Also, Freebox API answer bigger and bigger JSON objects (for example 'lanHost' object) and the core parsing tool  [JSON.sh](https://github.com/dominictarr/JSON.sh) used in this project reach its limit (for example, listing a 1000 movies directory on freebox storage will generate an ~1 mega byte JSON reply from the API and  [JSON.sh](https://github.com/dominictarr/JSON.sh) will take several minutes to parse it where `jq` took less than a second. 

So I think it's time to review the original mindset and if I still get no answer (and no help) from @JrCs , I will completly detach the 2 projects (mine and the original one)

Kind regards
nbanba

**Comment by Neustradamus** [comment]
@nbanb: Please do not mix, here, it is not your PR ^^

Here, it is a request to transfer this repository into an organization, and will add people to manage correctly the project.
When the new team will be here, it will be easy to manage the project.

**Comment by nbanb** [comment]
Hello 

@Neustradamus : I know that's not my last PR!
I was just talking to you personally ! (maybe it's not the best place..., ok !)

@Neustradamus ... Why ? Because you asked to transfer the repository to an organisation SO you must understand my feeling about this project where I wrote more that 95% of the code and where I'm the only effective maintainer since early 2020 to now (2024-10-24)...


Also, it's for explaning you what's today my global feeling are on the project and how much the actual project owner seems to be uninterrested by all the work which had been done (today the original author don't seems to have a freebox for its personal use and / or for testing purposes, so I think I can understand him...)

If it's easier for you to continue this thread in french (otherwise we can continue here), don't hesitate to open an issue here [issue](https://github.com/nbanb/fbx-delta-nba_bash_api.sh/issues) ,

Kind regards 
@nbanb

**Comment by JrCs** [comment]
Here the new organisation: https://github.com/freeboxos/freeboxos-bash-api

**Comment by nbanb** [comment]
Hi

Huge thanks @JrCs !
We'll join there !

Kind regards 
nbanba

**Comment by Neustradamus** [comment]
@JrCs: Thanks a lot for the transfer!

Have you sent a request to @nbanb to be owner?
Can you add me too?

Can you add you in public here because by default it is private:
- https://github.com/orgs/freeboxos/people

Thanks in advance.

**Comment by Neustradamus** [comment]
@JrCs: Thanks!
The future starts now :)

**Comment by Neustradamus** [comment]
@JrCs: I have sent you an e-mail, there is a problem, it is possible to have a change?
Thanks in advance.

**Comment by Neustradamus** [comment]
@JrCs: @nbanb and me, we always have the problem, can you change, like it was before your changes, our status:
- https://github.com/orgs/freeboxos/people

Thanks in advance.
