### ISSUE TITLE
authorize_application gets internal error followed by invalid request

### ISSUE THREAD

**Issue by Albirew** [freeboxos/freeboxos-bash-api#3]
May be due to an update of free's API

Here's what I get:

> $ source ./freeboxos_bash_api.sh
> $ authorize_application  'Albi.app'  'AlbiApp VDSL check'  '1.0.0'  'GNU Linux'
> Erreur interne: internal_error
> Please grant/deny access to the application on the Freebox LCD...

_granting access on LCD_

> Requête invalide (404): invalid_request
> Authorization
> $

App grant does appear on freebox LCD but there's nothing appearing on freebox app access management's tab, even after having selected 'yes'

**Comment by nbanb** [comment]
Hi

I cannot reproduce.
If it can be reproduced, maybe it' would be better to open a case at [Freebox Bugtracker](https://dev.freebox.fr/bugs), because after selecting YES on the LCD, the authorize_application function is only tracking the status from the freebox, throwing status to error output and printing your app id and token (no new interraction with freebox (except retrieving status) that could explane the application is not added by the Freebox to the application tab).

Kind regards
nbanba

**Comment by Albirew** [comment]
Hi

I will close this issue as it was made in 2016 and since then, i changed hardware (revolution -> delta) and software (self-made scripts -> HAss).

**Comment by nbanb** [comment]
Hi @Albirew 

Thanks for update and really, really really sorry for 8-9 years without answer ! 

Since less than half a day, I'm now one of the official maintener of the project, so I will try to answer new issues as fast as I can.

Please note that it's only 4 years I really started to develop and enrich this project (when FREE released Virtual Machines capabilities in freeboxos for freebox DELTA), so at the time you open the issue, this project was not maintained since years and did not support TLS nor PUT / DELETE methode (+ websocket API, openssl >1.1.1n, ...)

As you change your hardware to a DELTA which support virtual machines, maybe you should ***have a new look*** on this project which now support full filesystem management + full virtual machine management (add, modify, del, start, stop, access console or screen over websocket API, etc...) 

For example, here is a preview of my own VM listing on my DELTA : 

![image](https://github.com/user-attachments/assets/cc8fd1f7-cd19-46a8-9196-130f4a5c58c0)

and a preview of 1 VM detail : 

![image](https://github.com/user-attachments/assets/317e0b77-7d44-480e-a22b-a05f12444f87)


and a preview of an access to 1 VM console over Freebox websocket API (like an Out-Of-Band access) : 

![Capture d’écran du 2024-10-24 21-35-32 (copie)](https://github.com/user-attachments/assets/5601fd49-619d-4b49-bf08-c29eb6f940fe)



and a preview of the listing of 1 directory (where are stored all VM images) : 

![image](https://github.com/user-attachments/assets/e7c37766-ae59-4665-a219-e0e9ce17d300)

All frontend functions of this library can be used as autonomous program from your bash command shell, so don't hesitate to use it ! (and if any, to share the work you've done).

Thanks and kind regards
nbanba
